name: mosquitto
services:
  mosquitto:
    image: 'eclipse-mosquitto'
    container_name: mosquitto
    hostname: mosquitto
    restart: always
    environment:
      - TZ=${TZ:-America/New_York}
    ports:
      - 1883:1883/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/srv/$USER/docker/library/eclipse-mosquitto/latest/rootfs/data/mosquito:/mosquitto/data
      - /var/lib/srv/$USER/docker/library/eclipse-mosquitto/latest/rootfs/data/logs/mosquito:/mosquitto/log
      - /var/lib/srv/$USER/docker/library/eclipse-mosquitto/latest/rootfs/config/mosquito:/mosquitto/config
    networks:
      - mosquito

networks:
  mosquito:
    name: mosquito
    external: false
